### ISSUE TITLE
Update user guide

### ISSUE THREAD

**Issue by nexolute** [AY1920S1-CS2103T-W12-4/main#21]
See https://nus-cs2103-ay1920s1.github.io/website/schedule/week7/project.html#2-update-ug and our private Google Docs.

- [x] Change metadata (Fixed by #7)
- [x] Remove irrelevant UG (Fixed by #7)
- [x] Add UG for transaction (Fixed by #31)
- [x] Add UG for repeatable transaction (Fixed by #23)
- [x] Add UG for loans (Fixed by #84)
- [x] Add UG for budgeting (Fixed by #7)
- [x] Add UG for analytics (Fixed by #28)

**Comment by nexolute** [comment]
Finally, we can close this :+1:
