### ISSUE TITLE
Update developer guide

### ISSUE THREAD

**Issue by nexolute** [AY1920S1-CS2103T-W12-4/main#22]
See https://nus-cs2103-ay1920s1.github.io/website/schedule/week7/project.html#3-update-dg-user-stories-glossary-nfrs-use-cases and our private Google Docs.

- [x] Change metadata (Fixed by #25)
- [x] Add user stories for transaction
- [x] Add user stories for repeatable transaction (Fixed by #44)
- [x] Add user stories for loans
- [x] Add user stories for budgeting (Fixed by #25)
- [x] Add user stories for analytics
- [x] Add use cases for transaction
- [x] Add use cases for repeatable transaction (Fixed by #44)
- [x] Add use cases for loans
- [x] Add use cases for budgeting
- [x] Add use cases for analytics
- [x] Add glossary

**Comment by nexolute** [comment]
I am lazy to find tag the respective PR, but I know its done. So closed!
